services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    deploy:
      resources:
        reservations:
          devices:
          - capabilities:
            - gpu
            count: 1
            driver: nvidia
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 50m
  webui:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    deploy:
      resources:
        reservations:
          devices:
          - capabilities:
            - gpu
            count: 1
            driver: nvidia
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 50m
