services:
  api:
    command:
    - python3
    - main.py
    container_name: moneyprinterturbo-api
    image: ghcr.io/harry0703/moneyprinterturbo:latest
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 50m
    ports:
    - 127.0.0.1:8080:8080
    restart: always
    volumes: &id001
    - ./config.toml:/MoneyPrinterTurbo/config.toml
    - ./storage:/MoneyPrinterTurbo/storage
  webui:
    command:
    - streamlit
    - run
    - ./webui/Main.py
    - --server.address=0.0.0.0
    - --server.port=8501
    - --browser.serverAddress=127.0.0.1
    - --server.enableCORS=True
    - --browser.gatherUsageStats=False
    - --client.toolbarMode=minimal
    - --logger.hideWelcomeMessage=True
    - --server.showEmailPrompt=False
    container_name: moneyprinterturbo-webui
    image: ghcr.io/harry0703/moneyprinterturbo:latest
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 50m
    ports:
    - 127.0.0.1:8501:8501
    restart: always
    volumes: *id001
x-common-volumes: *id001
